### ISSUE TITLE
Ctrl+C missing in Qapple

### ISSUE THREAD

**Issue by AnalogRain** [audetto/AppleWin#1]
I can't use Ctrl+C in Qapple on Linux to exit the monitor or running BASIC code. Is this a bug or is there a different keybind I'm supposed to use?

**Comment by audetto** [comment]
WOW! Someone is using this project!
To be honest, I did not spend a lot of time figuring out the conversion of keys to apple keys and I am not surprised I have missed some.

Let me have a look.

**Comment by AnalogRain** [comment]
thanks, i wanted to use winapple but im on linux atm, and linapple is horribly out of date. it was dependency hell to compile tho :p

**Comment by audetto** [comment]
Will look at it tomorrow. I found that backspace is out of work as well.

Without being arrogant, there is not a single reason on earth to use linapple over qapple.
This code runs 99% the same emulator code of AppleWin so you are constantly uptodate.

You can still use AppleWin via wine which works, if you want.

**Comment by audetto** [comment]
Should be fixed now.
Ctrl works, but some more work is required to double check them all.

**Comment by AnalogRain** [comment]
Not sure how accurate you want to get but according to the Applesoft Basic Reference Manual you must hit return after typing ctrl-c
![image](https://user-images.githubusercontent.com/27089165/84807492-efd31a00-afcc-11ea-8ec6-21895f6b4be7.png)

**Comment by audetto** [comment]
I dont think this is relevant.
Ctrl-C is correct now. You can compare to AppleWin.

I am talking about more exoteric combination like Ctrl-Shift-Space or some other character not A-Z which is good now.

**Comment by AnalogRain** [comment]
gotcha, wasnt sure if u wanted full keycombo accuracy or ease of use ^^ this is fine and understandable tho
