### ISSUE TITLE
Refactor sdirectsound to allow multiple implementations

### ISSUE THREAD

**Issue by sh95014** [audetto/AppleWin#101]
When the SDL implementation would still "push" audio to SDL and I was adding the "pull"-based CoreAudio support, I deliberately tried to stay within the structure of the SDL code and #ifdef'ed my way around.

Now that the SDL implementation is also "pull"-based, we should be able to define a suitable base class and split up the implementations for cleanliness. Right now there are 19 #ifdefs in my version of `sdirectsound.cpp` which is quite ugly.

If you have some time to sketch out where you'd like a new base class to live (common?) I can attempt to write up a PR.

https://github.com/sh95014/AppleWin/issues/41

**Comment by audetto** [comment]
There is not a well defined interface for different frontends.

1. Some of it is `virtual` in the `Frame`
2. some of it is *link-time* like https://github.com/audetto/AppleWin/blob/master/source/linux/linuxinterface.h
3. and some via `static` https://github.com/audetto/AppleWin/blob/master/source/linux/paddle.h#L27

1 has its own issues (we need to revisit the Frame hierarchy), but probably if well done would be the best.

I think that if we fix the hierarchy, then we have a path for this too.

**Comment by sh95014** [comment]
Looks like https://github.com/audetto/AppleWin/pull/115 basically fulfills this?

I've split the CoreAudio implementation out of `sdirectsound.cpp` now.

**Comment by audetto** [comment]
I am pleased it made your life easier.
I still think the hierarchy of Frames should be revisited.

If you have other immediate suggestions, do comment here, or close it.

**Comment by sh95014** [comment]
Agreed that `sdlframe` should probably be refactored, as that's my only remaining dependency on the SDL port. I'll take another look at it when I get some time.

**Comment by sh95014** [comment]
ref: https://github.com/audetto/AppleWin/pull/124
