### ISSUE TITLE
ra2 seems to change the "current directory"

### ISSUE THREAD

**Issue by wn2000** [audetto/AppleWin#112]
The libretro core seems to have done a `chdir()` somewhere to where the `.dsk` file is located.
As a result, when I bring up RetroArch's menu, it cannot find its font and everything is displayed in some low quality bitmap font (see screenshot).
Also after saving a game-specific override, the file ended up being saved to `/path/to/dsk/file/config/AppleWin/game.opt`, so the next time RetroArch starts, it cannot find the override in its default location (`/path/to/retroarch/config/AppleWin/`).

Expected behavior: I do not expect the "current folder" to change when the core is running.

![image](https://github.com/audetto/AppleWin/assets/64153870/085e79f0-61d9-4772-803e-5dbdae8f4df1)

**Comment by audetto** [comment]
I agree with you 100%. Unfortunately AppleWin does and I never understood why and if it can be skipped.

I will try to remove it as a special case for libretro and see what happens.
