### ISSUE TITLE
ra2: Cannot map controls

### ISSUE THREAD

**Issue by wn2000** [audetto/AppleWin#113]
Sorry for another issue. But this is getting better and better so thanks for the work!

Anyway I just noticed that it's not possible to map controls in RA (it just shows `--` as in the ss).

And after attempting to select the `--` option RA seems to remember that, so upon exiting the menu A/B lost response.
I believe this won't be an issue when the controls are made mappable.

![image](https://github.com/audetto/AppleWin/assets/64153870/41d15a7f-dbb3-4a2d-8eca-5fa3b53ecacc)

**Comment by audetto** [comment]
I think I know what is happens

https://github.com/audetto/AppleWin/blob/04140c33aeba8a304d6f7c0b72b578455d8f8e2c/source/frontends/libretro/libretro.cpp#L202

I should call as well `RETRO_ENVIRONMENT_SET_INPUT_DESCRIPTORS`,.

I have already looked at it and I decided I did not need as it is super confusing, everything is an `unsigned` and documentation is zero.

https://github.com/libretro/fuse-libretro/blob/847dbbd6f787823ac9a5dfacdd68ab181063374e/src/libretro.h#L2725

I have looked at examples and can't really say I understood what these fields really mean.

**Comment by audetto** [comment]
I think I know what is happens

https://github.com/audetto/AppleWin/blob/04140c33aeba8a304d6f7c0b72b578455d8f8e2c/source/frontends/libretro/libretro.cpp#L202

I should call as well `RETRO_ENVIRONMENT_SET_INPUT_DESCRIPTORS`,.

I've added something, try if it works for you. Tomorrow I will double check everything is as expected.

**Comment by audetto** [comment]
Looks ok, except I can't use the buttons any more, but I am not sure. I will have to investigate.

**Comment by wn2000** [comment]
> Looks ok, except I can't use the buttons any more, but I am not sure. I will have to investigate.

It works very well for me. All buttons can be remapped as well.

**Comment by audetto** [comment]
Buttons only worked for the standard joypad, not the analog one. But double check.

**Comment by wn2000** [comment]
This has worked very well with the latest commit. Thanks!
