### ISSUE TITLE
sa2: Certain keyboard input does not work

### ISSUE THREAD

**Issue by wn2000** [audetto/AppleWin#114]
Continuation from #111. 

The issue:

Keyboard inputs do not work in sa2 imgui version. They do work in the sa2 `--no-imgui` version.

Platform is an arm based Linux with KMSDRM and GLES2, no X.

Possible cause:

https://github.com/audetto/AppleWin/blob/eb550570203aa6a5fe82701959f0b582a4b78624/source/frontends/sdl/imgui/sdlimguiframe.cpp#L248-L250

In this switch block `io.WantCaptureKeyboard` is always true even when no ImGui settings window is active.
So all key events do not get passed beyond this point.

Commenting out this block seems to resolve the issue.

**Comment by audetto** [comment]
The code comes from ImGui's doc:

https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-how-can-i-tell-whether-to-dispatch-mousekeyboard-to-dear-imgui-or-my-application

https://github.com/ocornut/imgui/blob/6addf28c4b5d8fd109a6db73bed6436952b230b2/examples/example_sdl2_opengl2/main.cpp#L89

I think you should open an Issue on ImGui asking why `io.WantCaptureKeyboard` is always true, with a description of your system.
