### ISSUE TITLE
Disk Options?

### ISSUE THREAD

**Issue by akator70** [audetto/AppleWin#118]
I'm running this on Ubuntu 23.10 on a RPi4.  It works but I'm having some issues with disk loading.  I'm specifically using the "sa2" SDL version, although I have also tried the others without success.

- All normal Function Keys work as expected (as with AppleWin on WIndows) except for F3 and F4.  I've tried every key combination I can think of but neither of these will bring up the Disk selection to load a new disk.
- If there's a way to use the settings menu to load a disk, I haven't found it.
- The only option I've found to load a disk is to "drag and drop" from the desktop.  

Is there a way to load disks into sa2 _without_ using the desktop?  I was hoping to run this in fullscreen without a desktop at all.  It loads and runs fine without a desktop except for the inability to choose and load disks (or HDs).

Thanks!

**Comment by akator70** [comment]
Great work on this, it's very impressive.

D&D is definitely a cool thing to have, but I think a file dialog would be an excellent addition.  A file dialog would make full screen use that much more immersive.  Sa2 already runs without a full desktop so a file dialog would make it possible to create a "dedicated" Apple II µSD card for the RPi and other SBCs.

**Comment by audetto** [comment]
Will look into it. How do you even run it without desktop?

**Comment by akator70** [comment]
With all of the dependencies installed, it's pretty easy:

Disable the desktop at boot: 
sudo systemctl set-default multi-user.target

Reboot, then from the CLI:
startx /path/to/binary/sa2

It runs perfectly,only without the ability to load different disks after launch.

**Comment by audetto** [comment]
Done.
