### ISSUE TITLE
sa2: stopAudio() and writeAudio() have been deleted but are still declared

### ISSUE THREAD

**Issue by sh95014** [audetto/AppleWin#121]
The following functions had been deleted but are still declared in `sdirectsound.h`:
```c++
  void stopAudio();
  void writeAudio(const char * deviceName, const size_t ms);
```

https://github.com/audetto/AppleWin/pull/115/files#diff-091991c6c477d1db671fcf36908979cd93b8f62bfe07444a84effc0eb75f07c5

Also:

```c++
  void ResetUnderrruns();
```

in `dsound.h` has one too many r's.

**Comment by shuang886** [comment]
BTW https://github.com/audetto/AppleWin/commit/bfd2b8ade1272fb4e53946d74e573def34830d09 doesn’t seem to fix the spelling of `ResetUnderrruns()`.

**Comment by sh95014** [comment]
BTW https://github.com/audetto/AppleWin/commit/bfd2b8ade1272fb4e53946d74e573def34830d09 doesn’t seem to fix the spelling of `ResetUnderrruns()`.
