### ISSUE TITLE
sa2 speed tab issues

### ISSUE THREAD

**Issue by xandark** [audetto/AppleWin#126]
In sa2, which is working great BTW especially the audio!, I notice that in the Settings -> Speed tab, if I play with the Speed slider and want to get it back to the normal 1Mhz speed, clicking the Reset speed button at the bottom doesn't do anything that I can tell. And moving the slider around, it's not clear to me what the number in the slider corresponds to. Is it a multiplier to the base clock? 

This is such a cool GUI, that I'd like to see more speed buttons that I could click, like 1Mhz, 2Mhz, and also that I could slow it down to like 100Hz if I wanted to.

**Comment by audetto** [comment]
The button has been renamed to `Reset stats`.
The formula is here

https://github.com/AppleWin/AppleWin/blob/1e444fbb9febb73f855cde09f5eafe436b6ea71c/source/Core.cpp#L218

There is a long thread in AW about allowing slower speeds

https://github.com/AppleWin/AppleWin/issues/1254

I could add some buttons to ease setting common multipliers.
At the end the speed has to be an exact multiple of the audio sample rate.

**Comment by xandark** [comment]
Okay, I see. And yes, having some extra buttons to ease setting common multipliers would be perfect. I just want to be lazy and not have to think about numbers, just click a button and be done with it.

**Comment by xandark** [comment]
Great, thanks!
