### ISSUE TITLE
ra2 core: audio selection problem.

### ISSUE THREAD

**Issue by audetto** [audetto/AppleWin#139]
AW has recently converted the speaker to dual (with left = right), so the trick to select the source based on the number of channels (1 or 2) no longer works.

**Comment by sfatula** [comment]
Does this prevent audio from working at all? On a Vero V device, I am unable to get any sound at all from AppleWin. mame sound works fine. I can play samples to the device I am selecting from speaker-test -D, but no sound comes from AppleWin games via libretro. Just curious if what you are messaging yourself for might have anything to do with it? Playing to an AVR as I have a projector

**Comment by audetto** [comment]
You must select mockingboard always. And ideally remove the mockingbord
from the slot.

I will try to find some other way to differentiate them.

**Comment by sfatula** [comment]
Omg, after a ton of hours trying to get ra2 to play audio, removing from the slot was the key! Audio works now!! Thanks.

**Comment by audetto** [comment]
With the proposed PR it works again.
And, do you know you can use R2 to quickly alternate between MD and Speaker?

**Comment by sfatula** [comment]
Hopefully AppleWin works with xboxdrv, R2 for now does that but hoping to remap things so I can play games (and there are huge numbers) that work with joysticks BUT also need some keyboard commands. I don't want a keyboard! Some of the libretro modules support assign keyboard keys to buttons but apparently not AppleWin so I need to go the xboxdrv route.

**Comment by audetto** [comment]
We can discuss that elsewhere.
