### ISSUE TITLE
libpcap is still required if libslirp is found

### ISSUE THREAD

**Issue by ryandesign** [audetto/AppleWin#140]
I'm on Linux Mint trying to build your latest code from git.

My understanding is that you require either libslirp or libpcap:

```
-- Checking for one of the modules 'slirp'
CMake Warning at source/CMakeLists.txt:10 (message):
  'libslirp' not found.  Will use 'libpcap' instead


-- Checking for one of the modules 'libpcap'
CMake Error at source/CMakeLists.txt:24 (message):
  Cannot locate 'libpcap-dev'


-- Configuring incomplete, errors occurred!
```

So I installed libslirp-dev by running:

```
sudo apt install libslirp-dev
```

But I still get this error:

```
-- Checking for one of the modules 'libpcap'
CMake Error at source/CMakeLists.txt:24 (message):
  Cannot locate 'libpcap-dev'


-- Configuring incomplete, errors occurred!
```

It goes away if I run:

```
sudo apt install libpcap-dev
```

but should I really have to install both of them?

**Comment by audetto** [comment]
It is a bit different.

`slirp` is optional, `pcap` compulsory

There are no `#iddef`s in code to compile it out.

**Comment by audetto** [comment]
What happens is this: `pcap` is compulsory and must be linked, but it `slirp` is present, it will not be used (nor usable).

I know what one might think, but the cost of installing the lib it is less than the profit of removing it.
I could at least make it selectable, which would at least remove the apparent nonsense.
