### ISSUE TITLE
sa2: Remove Dear ImGui Demo

### ISSUE THREAD

**Issue by ryandesign** [audetto/AppleWin#141]
In sa2, the Help menu has an item Demo which opens a demo of Dear ImGui.

There's also a Show Demo checkbox in Settings that does the same thing.

Doesn't seem like either of those should be there.

**Comment by audetto** [comment]
2 of them is indeed too many.
I will keep the one in `Help`, I use it to understand what is possible or not with `ImGui`.

**Comment by ryandesign** [comment]
It should be hidden behind some non-default developer-only build flag. Users have no reason to see this demo.
