### ISSUE TITLE
How to start with debugging enabled?

### ISSUE THREAD

**Issue by markjfisher** [audetto/AppleWin#143]
I've got some breakpoints setup but they don't fire unless the debugger is open.
I'm trying to debug some startup issues, but without being able to get the debugger open, they don't fire.

Is it possible to start with the debugger enabled immediately so any Cn00 access can be trapped on boot up (for instance).

**Comment by audetto** [comment]
2 (untested) options:

1. I add a new flag `--paused`
2. What if you set the breakpoint, and then `ResetMachineState`? `Restart` will erase all breakpoints.

Tell me how it goes.

**Comment by markjfisher** [comment]
ResetMachineState kind of works, in that the BPs are hit, but because the state was reset it's not the same conditions I'm trying to capture.

I've written a SmartPort layer for AppleWin, the application running is rebooting with certain state for the machine to boot/read from the attached SP connection (FujiNet emulator), but upon loading the disk it hits 0000 and stops.
Same application/code/SP emulator card in Windows version works fine (but doesn't auto boot like the Linux port does), so just trying to isolate what's causing the reboot and why it's consistently (loading any disk from SP) jumping to 0000.

**Comment by audetto** [comment]
I will add a flag.

For now, change this
https://github.com/audetto/AppleWin/blob/87ab72a249ac741691fba05c8240168119c11144/source/linux/context.cpp#L99
to `MODE_PAUSED`.

Then you need to use the debugger to start it via `Continue`.

This is applied after each `Restart` too.

**Comment by markjfisher** [comment]
Awesome, thanks.

**Comment by markjfisher** [comment]
This really helped pin point the issue thanks. Turns out I needed to set appropriate memdirty pages, as the ram was swapping out and removing mem values I'd set.

**Comment by audetto** [comment]
There is now a command line flag `--paused` and anyway a UI setting to select when the next Reset will do.

**Comment by markjfisher** [comment]
On fire today! Thanks.
