### ISSUE TITLE
libretro: play games without a keyboard.

### ISSUE THREAD

**Issue by audetto** [audetto/AppleWin#148]
From https://github.com/audetto/AppleWin/issues/139#issuecomment-1986960448

It might be useful to remap some keys to the gamepad so a keyboard is not needed.

I think it is a good idea.
Can you give more details. Is there another `libretro` core which allows it?

**Comment by sfatula** [comment]
I believe fmsx does.  And Dosbox pure. There was at least one more, it was even in the retroarch core doc but can't locate it right now. 

So, think loderunner as an example. Using the joystick works wonderfully. But you get stuck and you have to abort the level and lose a life. That's takes a ctrl-a, meaning, hooking up a keyboard just so you can type a ctrl-a. 

There are other games (esp some SSI games) where there are keyboard commands, but they are very limited in number. 

If a game was truly keyboard, then, you'd have to use a real keyboard of course if it had a lot of commands like typing names, etc. (thinking Wizardry).

**Comment by audetto** [comment]
If `CTRL-A` and `-R` do not work, it is a bug. Their scancode is 1 and 12.
Uncomment line 221 of `game.cpp` and copy here the output when you press these keys.

**Comment by audetto** [comment]
And now, start must be pressed twice in 1 second to restart.

**Comment by sfatula** [comment]
I tried with ascii keyboard core setting or not (typed on KB), key code or not via xboxdrv and gamepad to send codes (they all send except control keys), just could never get it to work and you can't beat all the levels without a few times needing control-a. I will change the logging line (it's 222 in my version) and recompile and post back.

**Comment by audetto** [comment]
I think this is the line in `fuse` you refer to

https://github.com/libretro/fuse-libretro/blob/847dbbd6f787823ac9a5dfacdd68ab181063374e/src/libretro.c#L35

If I read this correctly, once they are set, they override whichever meaning the joypad button already had.

I don't know, it seems such an obvious requirement, that `libretro` should provide it once and for all cores. Are we sure, it is not already available?

**Comment by sfatula** [comment]
So, here's some log entries:

`RA2: processKeyDown - 00 132 00 00
RA2: processKeyDown - 00 132 00 00
RA2: processKeyDown - 00 132 00 00
RA2: processKeyDown - 00 132 00 00
RA2: processKeyDown - 00 132 00 00
RA2: processKeyDown - 00 132 00 00
RA2: processKeyDown - 00 132 00 00
RA2: processKeyDown - 00 132 00 00
RA2: processKeyDown - 00 132 00 00`

An entry is made when holding down the left control key in this case, but, then any key with it is missed and has no log entry. So, no combo apparently.

Pretty sure there is no all cores feature to type a keyboard key from a controller button. In the manual, they suggest using xboxdrv. That does work but it's a lot of work.

**Comment by audetto** [comment]
As you can see, there is no early exit in that function. It sounds an issues with the frontend.

Which one are you using?

**Comment by sfatula** [comment]
ra2 via retroarch

**Comment by audetto** [comment]
It is done to a setting in retroarch.

AppleWin recommends to enable `Game Focus Mode`

https://github.com/audetto/AppleWin?tab=readme-ov-file#ra2

For the exact behaviour, check the libretro doc or forums.

**Comment by sfatula** [comment]
Yes, I am aware of game focus mode, on or off makes no difference, I cannot abort the level with control-a.

**Comment by sfatula** [comment]
Helpful to know it works for you, will have to look elsewhere then as it definitely does not work for me. Strange!

**Comment by audetto** [comment]
Unless more evidence points to an AppleWin issue, I will close this.
