### ISSUE TITLE
Suggestion: add a menu item that displays all the keyboard shortcuts

### ISSUE THREAD

**Issue by xandark** [audetto/AppleWin#149]
It would be great to have some kind of windowoid that would show all the keyboard shortcuts. I know from using the Windows-based version of AppleWin that F2 is reset and F6 is full-screen, but it would be great to be able to discover what the shortcuts are. My suggestion is to add a menu item to the Help menu that displays a windowoid with all the keyboard shortcuts. Because right now, I have to guess.

**Comment by audetto** [comment]
I think it is a very good suggestion.

Here what it is at the moment

![Screenshot from 2024-03-17 15-28-38](https://github.com/audetto/AppleWin/assets/212523/98d84160-c3f2-4b84-bf94-0042179211c0)

I was surprised by some of them, and I might revisit the choices.

**Comment by xandark** [comment]
Looks good!

**Comment by xandark** [comment]
It would be nice to have an F-key that allows me to load a disk in drive 1 or drive 2. That's an operation that I do a lot.

**Comment by xandark** [comment]
Not sure I need F3 to quit, as Alt-F4 is the standard quit.

**Comment by sfatula** [comment]
> It would be nice to have an F-key that allows me to load a disk in drive 1 or drive 2. That's an operation that I do a lot.

Yes, there are some games that require more than 2 disk, not sure how many but Wizardry is one of them. Swapping disks not good enough.

**Comment by audetto** [comment]
Disks: at the moment it is necessary to use the mouse to load disks. Either to open the file dialog, or to select the destination o f the drag and drop.
You are asking for a F-key to open the File Dialog and then still use the mouse. Correct?
If you always put the floppies in the same disk, I suspect a d&d is much easier, or you disagree?

Speed: AppleWin
https://github.com/audetto/AppleWin/blob/ca0d0b2665d6009a5a7700c3ec5e51aa85d0b2b1/help/keyboard.html#L62-L67
maybe I can do the same.

**Comment by sfatula** [comment]
Speed like AppleWin has it is good yes. What is "D&D"? For me (not other guy maybe), F-Key to open disk dialog is ok by me.

**Comment by audetto** [comment]
Drag and Drop.
Select the destination disk here (under `D&D`)

![image](https://github.com/audetto/AppleWin/assets/212523/fc85ab94-1da9-4174-9273-8bcf5b92987d)

and just drag a file from your desktop file browser.
It works with HD and FP (but the file dropped must be of the correct type).

**Comment by sfatula** [comment]
I kind of like the open dialog over drag and drop as it defaults it seems to the same folder as existing disks, making it less work than opening up a file manager to browse through. Still, would like that screen you showed to be assigned to an F key

**Comment by xandark** [comment]
> You are asking for a F-key to open the File Dialog and then still use the mouse. Correct?

Yes, that's right. In the original AppleWin, there were the icons along the side of the window so that I could just click the icon for the drive and up pops a standard dialog window where I can select the image. 

> If you always put the floppies in the same disk, I suspect a d&d is much easier, or you disagree?

D&D isn't my workflow, TBH. 
Clicking on an icon to bring up the last browsed directory of images worked great for me. If there's no clickable icon, then pressing a F-key would be good.

**Comment by xandark** [comment]
I should close this, it satisfies the initial issue, thanks!
