### ISSUE TITLE
Wish: render video output using OpenEmulator shader code

### ISSUE THREAD

**Issue by xandark** [audetto/AppleWin#162]
I'm sure you've seen OpenEmulator's output and how fantastic it is. What is the feasibility of adapting that for AppleWin?

https://zellyn.com/apple2shader/

**Comment by audetto** [comment]
Probably will close as a won't fix.

You should re-open this issue in the original AppleWin project.

Anyway, are you able to put a link to the exact video rendering routine you are referring to?

**Comment by xandark** [comment]
Okay, I'll re-open it there.

The exact video rendering shader code that I referred to is [here](https://github.com/zellyn/apple2shader). It's a port of the original OpenEmulator code to interactive Javascript.

It takes 1-bit Apple II video imagery, such as [this example](https://github.com/zellyn/apple2shader/blob/master/images/airheart-560x192.png), and converts it to a great NTSC CRT likeness:

![Screenshot 2024-04-23 (20:44:15)](https://github.com/audetto/AppleWin/assets/5048913/ca9e0f46-066d-442b-9ada-604028416397)

[This page](https://zellyn.com/apple2shader/) allows one to play with all of the NTSC CRT variables.

The Javascript code with the embedded shader code is [here](https://github.com/zellyn/apple2shader/blob/master/screenEmu.js)

The original implementation is found [here](https://github.com/openemulator/openemulator).

**Comment by audetto** [comment]
Interesting.
My knowledge of the Apple video rendering routines is very limited.

Moreover, I only had a green monochrome monitor, so I have no idea what it really looked like on anything different.

But they guys at AppleWin have done a lot of work on this, they might be able to provide more constructive comments.

**Comment by xandark** [comment]
Yes, it's super cool, and I added to the 10-year old thread on AppleWin regarding video rendering, but I'm not expecting them to move forward on this issue, nor the long-standing emulated disk drive sounds request either. But I'll put it out there.

**Comment by sh95014** [comment]
The "10-year old thread on AppleWin" is https://github.com/AppleWin/AppleWin/issues/254

**Comment by audetto** [comment]
I will close this, as it is not the appropriate location.
