### ISSUE TITLE
applen alternately displays wrong text page when running A2osX text-based disk OS

### ISSUE THREAD

**Issue by xandark** [audetto/AppleWin#23]
First of all, this is such a cool project! I am having so much fun running AppleWin natively on Linux and it built without a hitch on my Kubuntu 20.04 system, using the packages I found in raspbian.list.txt. 

I was blown away by how well I could run Aztec in the terminal and still make out the gist of the game. My next step was to run a text-based shell, like the currently-in-development A2osX. 

I found that running [this floppy image](https://github.com/A2osX/A2osX/blob/master/.Floppies/STABLE.140.po), which is an 80-column mode shell, resulted in my virtual Apple II display flickering between text pages way too much. It seems that when the input cursor is on an odd column, the display shows text page 2, which is garbage. Just advancing the cursor by one brings back the expected display of text page 1. Back and forth, it's unusable.

I tried a regular ProDOS disk, and I didn't notice this behavior in its 80-column display. 

Regardless, I really hope that this work can be merged back into AppleWin.

**Comment by audetto** [comment]
Have you tried to widen the terminal? https://github.com/audetto/AppleWin/blob/master/linux.md#applen
Only in HiRes graph. Try ALT or CTRL, not all terminals use the same code for these keys.

About A2osX, I saw it, will try to figure this out.

**Comment by audetto** [comment]
A couple of things for you

- it is a bit slow, so you can use: ``./sa2 --imgui --gl-swap 0 --fixed-speed`` for maximum speed
- caps lock to get lower case
- this line https://github.com/audetto/AppleWin/blob/master/source/frontends/ncurses/nframe.cpp#L144 causes the page mode switch. I am not sure, I copied it from ``linapple``: https://github.com/dabonetn/linapple-pie/blob/c22ba0c3ad6c317b4f13486b7ff06a340c831122/src/Video.cpp#L1641 and https://github.com/dabonetn/linapple-pie/blob/c22ba0c3ad6c317b4f13486b7ff06a340c831122/src/Video.cpp#L1938
- maybe I got it wrong.

**Comment by audetto** [comment]
linapple had a huge number of issues.
Should be fixed now, but better to reuse AW logic from https://github.com/AppleWin/AppleWin/blob/master/source/NTSC.cpp#L77

**Comment by xandark** [comment]
Yep, that fixed it, great, thanks!

**Comment by xandark** [comment]
And yes, I did widen the terminal view, that's pretty cool too.
