### ISSUE TITLE
[Feature Request] Adding an option to active enhanced speed disk on SDL2 port.

### ISSUE THREAD

**Issue by FredBezies** [audetto/AppleWin#33]
Hello.

I noticed that only QT port provides enhanced speed disk. I do not found an option to activate this useful feature in the SDL2 port.

Loading some games with SDL2 port is slower compared to QT port and it is annoying.

Thanks for adding this feature.

**Comment by audetto** [comment]
Try now.
Logic might need some improvement.

**Comment by FredBezies** [comment]
Well, loading time was divided by nearly 2. Without enhanced speed, loading game and loading a level: 39s

With enhance speed, loading game and a level: 20s...

It is "Attack of the PETSCII Robots" -> http://www.the8bitguy.com/26654/petscii-robots-for-apple-ii-now-available/

Setting is easy to find. Thanks for adding the feature.

**Comment by audetto** [comment]
I am not too sure I like the implementation.
I have not found how to download the game.

Could you please `git pull` and compare these 2 as well

- how long it takes in `AppleWin`
- how long it takes with `./sa2 --imgui -r "Configuration.Enhance Disk Speed=0" --fixed-speed --gl-swap 0`

**Comment by FredBezies** [comment]
It is a commercial game release in 2021. See: https://www.mobygames.com/game/apple2/attack-of-the-petscii-robots

* AppleWin (using Wine 6.9). Using enhanced speed disk, then loading the game then a level: 9s + 3s. ; Authentic speed disk: 38s (because of wine?) + 8s.
* sa2: with --fixed-speed? 
 Loading game then a level: 3s + 1s 
 Removing --fixed-speed option: 23s + 8s ; with --fixed-speed: 3s + 1s

Hope it helps.

**Comment by audetto** [comment]
At https://github.com/audetto/AppleWin/commit/c3e8bb94a2019c623edacf4b7c019b2b15f0d471 I have rewritten the full speed logic. Very similar to AppleWin now.

Exposed the speed adjustment in the UI and used `ScrLk` to enable maximum speed.

**Comment by FredBezies** [comment]
It is working perfectly and setting is easy to find! Thanks a lot. Time to close this bug?
