### ISSUE TITLE
[git][sdl2]Cannot boot automatically on prodos boot disk on restart with Applewin commit cd0a18d

### ISSUE THREAD

**Issue by FredBezies** [audetto/AppleWin#35]
Hello.

I noticed a regression introduced between commit db8997d and commit cd0a18d. Disk drive are not started after I asked for a computer reboot. Status is OFF instead of read. It also reset the content of disk drive 1. Ouch!

Even after I inserted a bootable prodos disk image and reset the emulator, nothing happens.

I set up an Apple IIe Enhanced with Mockingboard in both slot 4 and 5. Both disk drives are connected to slot 6. Enhanced speed is also on. 

Log is empty :(

I tried to build commit 7ae280a, so I cannot say if this one or the other is guilty for the not starting disk drive.

I got this building error:

```
[ 61%] Linking CXX shared library libappleii.so
[ 61%] Built target appleii
make: *** [Makefile:156 : all] Error 2

```
Sorry.

**Comment by audetto** [comment]
I see.
I was using a function that has been hidden, and the replacement has a side effect.
I need to debug in Windows, will do it tomorrow.

**Comment by FredBezies** [comment]
> I see.
> I was using a function that has been hidden, and the replacement has a side effect.

Ok.

> I need to debug in Windows, will do it tomorrow.
> 
> This should work [db8997d](https://github.com/audetto/AppleWin/commit/db8997d6523eff3164483b8647a820638159c8d4)

I'm using a build based on this commit.

**Comment by FredBezies** [comment]
Thanks for the fix!
