### ISSUE TITLE
Minimum set of binaries for a linux package?

### ISSUE THREAD

**Issue by nerun** [audetto/AppleWin#38]
In `linux.md` is said that *libapple* (surely `build/source/libappleii.so`) plus the 4 frontends are the core of AppleWin emulator for Linux environment. I just separated *libappleii.so* and *qapple* binary to create a basic package. What i want to know is if other files are needed besides this one.

In AppleWin for Windows the release package has at least 3 other files:
* A2_BASIC.SYM
* APPLE2E.SYM
* DELREG.INF

Do i need to put them inside my package? What they are intended for?

**Comment by nerun** [comment]
Thank you! Closing issue.

**Comment by audetto** [comment]
not mine

https://packages.ubuntu.com/search?searchon=contents&keywords=libapple-trailers.so&mode=exactfilename&suite=hirsute&arch=any

**Comment by nerun** [comment]
### Suggestion
Change debian package name from `applewin-1.30.3.0-Linux.deb` to `applewin_1.30.3.0_all.deb` this is the proper format. The `_all` means it runs in all architectures, change to amd64 if it works just in x86_64 etc.
