### ISSUE TITLE
[Bug] Open Apple key not working

### ISSUE THREAD

**Issue by DivergentClouds** [audetto/AppleWin#4]
I was attempting to use the Merlin assembler and the manual says you can use Open Apple + Q to quit from the editor, in AppleWin (main) thats left alt with Closed Apple being right alt. Pressing that key combination will just type Q. I assume neither are implemented however I haven't found a way to test Closed Apple yet.

**Comment by audetto** [comment]
will find some key combination.
I think the only way now to to use a joypad.

**Comment by AnalogRain** [comment]
why won't the alts work? is it a Qt thing?

**Comment by audetto** [comment]
Left Alt behaves strangely in Qt.

I used Left / Right Ctrl. Not the most potable solution, but check.

**Comment by AnalogRain** [comment]
I'm unsure if anything requires ctrl and an apple key at the same time, but if not perhaps holding down right-alt along with one of the ctrl keys could work.

**Comment by audetto** [comment]
guess this is the reason why AW uses Alt...
Let me try to find another character.

**Comment by AnalogRain** [comment]
Not all keyboards have AltGr, maybe just Right Alt and Menu?

**Comment by audetto** [comment]
I do not have right alt so I cannot test.

**Comment by audetto** [comment]
For information

https://forum.qt.io/topic/116042/missing-keyevents-for-qt-key_alt

**Comment by audetto** [comment]
I have moved to AltGr and Menu pending a solution about Alt.

**Comment by audetto** [comment]
I guess we can close this.

The ImGui version uses Left and Right Alt (like AW)

Qt still uses different keys as I was not able to use Alt reliably.
