### ISSUE TITLE
Uthernet II: compile with Visual Studio

### ISSUE THREAD

**Issue by audetto** [audetto/AppleWin#59]
Moving to an issue here.
There is a branch for this project.

https://github.com/audetto/AppleWin/tree/u2win/source

One needs to enable the card with a change at around https://github.com/audetto/AppleWin/blob/9a2e1a7af609e6ed098f7c346b5b83f7d7c03412/source/CardManager.cpp#L94
```
	case CT_Uthernet:
		m_slot[slot] = new DummyCard(type, slot); // INITIALISE TFE
		m_slot[slot] = new Uthernet2(slot); // Use the U II CARD
		break;
```

I haven't been able to run it yet, because I run inside QEMU and lipcap fails.

**Comment by audetto** [comment]
I think this might have to be fixed:

https://github.com/audetto/AppleWin/blob/9a2e1a7af609e6ed098f7c346b5b83f7d7c03412/source/linux/network/uthernet2.cpp#L643-L647

Windows seems to use `WSAGetLastError` to check the socket status
https://docs.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-connect

**Comment by oliverschmidt** [comment]
> I think this might have to be fixed [...]

Of course.

**Comment by audetto** [comment]
And you need https://github.com/audetto/AppleWin/blob/9a2e1a7af609e6ed098f7c346b5b83f7d7c03412/source/linux/network/uthernet2.cpp#L191
to change to `CT_Uthernet` to fool AW's config. And the load/save state file wont work.

I still get an Access Violation but VS does not tell me where...

**Comment by audetto** [comment]
I've implemented a simple Load/Save state (just the presence of the card, so make sure you save BEFORE the code initialises the card).

And forces AW to use U II when it is selected via the GUI (existing U 1 save states will continue to use U1)

**Comment by oliverschmidt** [comment]
I "can" reproduce the (presumably same) access violation

```
Exception thrown at 0x00FAF339 in AppleWin.exe: 0xC0000005: Access violation writing location 0x00EB6986.
```

with the call stack

```
 	AppleWin.exe!memcpy(unsigned char * dst, unsigned char * src, unsigned long count) Line 636	Unknown
 	AppleWin.exe!TfePcapPacketHandler(unsigned char * param, const pcap_pkthdr * header, const unsigned char * pkt_data) Line 483	C++
 	[External Code]	
 	wpcap.dll![Frames below may be incorrect and/or missing, no symbols loaded for wpcap.dll]	Unknown
 	AppleWin.exe!tfe_arch_receive_frame(TFE_PCAP_INTERNAL_tag * pinternal) Line 503	C++
 	AppleWin.exe!tfe_arch_receive(unsigned char * pbuffer, int * plen, int * phashed, int * phash_index, int * prx_ok, int * pcorrect_mac, int * pbroadcast, int * pcrc_error) Line 592	C++
>	AppleWin.exe!TFEBackend::receiveOne(const unsigned char * mac, unsigned char * & data, int & size) Line 70	C++
 	AppleWin.exe!Uthernet2::receiveOnePacketMacRaw(const unsigned int i) Line 377	C++
 	AppleWin.exe!Uthernet2::receiveOnePacket(const unsigned int i) Line 447	C++
 	AppleWin.exe!Uthernet2::readSocketRegister(const unsigned short address) Line 723	C++
 	AppleWin.exe!Uthernet2::readValueAt(const unsigned short address) Line 758	C++
 	AppleWin.exe!Uthernet2::readValue() Line 796	C++
 	AppleWin.exe!Uthernet2::IO_C0(unsigned short programcounter, unsigned short address, unsigned char write, unsigned char value, unsigned long nCycles) Line 1024	C++
 	AppleWin.exe!u2_C0(unsigned short programcounter, unsigned short address, unsigned char write, unsigned char value, unsigned long nCycles) Line 1043	C++
 	AppleWin.exe!Cpu65C02(unsigned long uTotalCycles, const bool bVideoUpdate) Line 238	C++
 	AppleWin.exe!InternalCpuExecute(const unsigned long uTotalCycles, const bool bVideoUpdate) Line 517	C++
 	AppleWin.exe!CpuExecute(const unsigned long uCycles, const bool bVideoUpdate) Line 632	C++
 	AppleWin.exe!ContinueExecution() Line 219	C++
 	AppleWin.exe!EnterMessageLoop() Line 315	C++
 	AppleWin.exe!WinMain(HINSTANCE__ * passinstance, HINSTANCE__ * __formal, char * lpCmdLine, int __formal) Line 540	C++
 	[External Code]	
```

However, the address stated above is the very one given as second parameter to `myNetworkBackend->receiveOne(mac, data, size))`. The VS debugger has no issue at all writing to that address. So I have no idea what's going wrong. I can be sure that my general libpcap setup is okay, because the Uthernet I emulation worked just fine a few minutes ago - with the same AW source code just before hacking in the Uthernet II usage as described above.

**Comment by audetto** [comment]
It is code I never run...

Anyway, I will have to see if VirtualBox can handle libpcap.
But for you right now, if you could skip the DHCP code and MacRaw, then you can go to the TCP and see if the rest works.
The emulation does not need the IP address to work in TCP mode.

**Comment by oliverschmidt** [comment]
> But for you right now, if you could skip the DHCP code and MacRaw, then you can go to the TCP and see if the rest works.
The emulation does not need the IP address to work in TCP mode.

Thanks for the hint, I thought about that myself. Depending on how desperate I get getting my Apple II hybrid program to work on Windows I might try...

**Comment by audetto** [comment]
The code cant be that bad. It works in linux (with the TFEBackend).

Unfortunately my Windows VirtualBox died badly, so I cannot help you in debugging.

**Comment by oliverschmidt** [comment]
> The code cant be that bad. It works in linux (with the TFEBackend).

For sure. On the other hand, the Uthernet I code doesn't show the issue, so <....>

**Comment by audetto** [comment]
Don't trust anyone!
Given the fix I just committed I have no idea how I came to that conclusion!

**Comment by oliverschmidt** [comment]
Sorry for being slow on take up, but - what fix are you referring to?

**Comment by audetto** [comment]
Here: https://github.com/audetto/AppleWin/tree/u2win

This contains all the changes you suggested, plus some more from me, and it fixes the big access violation.

If you edit more, rebase on top of it.
Moreover, you should not need any other change to enable U 2.

**Comment by oliverschmidt** [comment]
I can confirm that the access violation is gone :-)

**Comment by oliverschmidt** [comment]
Just for the record. There are 4 warnings left:

```
...\source\linux\network\uthernet2.cpp(96,49): warning C4267: 'initializing': conversion from 'size_t' to 'uint16_t', possible loss of data
...\source\linux\network\uthernet2.cpp(96,49): warning C4267: 'initializing': conversion from 'size_t' to 'const uint16_t', possible loss of data
...\source\linux\network\uthernet2.cpp(110,34): warning C4267: 'argument': conversion from 'size_t' to 'const uint16_t', possible loss of data
...\source\linux\network\uthernet2.cpp(969,48): warning C4267: '=': conversion from 'size_t' to 'uint16_t', possible loss of data
```

I don't know of any way beside suppressing the warnings - and in general they seem sort of correct...

**Comment by oliverschmidt** [comment]
I can confirm that the current build allows to cleanly swtich between Uthernet and Uthernet II. After all those years the drop down combo box finally makes sense ;-)

However, I noticed a strange behavior. When I switch to the '\Device\NPF_Loopback' device, then the next try to bring up the Ethernet selection dialog triggers this dialog:
 
![image](https://user-images.githubusercontent.com/2664009/149202980-9cad2f89-155c-44d4-93f1-17c567213d6d.png)

The only way to get back to normal is then to manually modify the registry settings.

Talking about that dialog:
- I don't want to activate 'TFE support', I want to activate 'Uthernet support'.
- I don't want to 'activate network wirth VICE', I want to 'activate network with AppleWin'.
- The URL given isn't clickable nor selectable.
- The URL isn't HTTPS (no good in 2022).
- The URL just gives a 404.

**Comment by audetto** [comment]
I agree with everything. And this is why I told you at the begin, that this code has to go, and a refactoring of Uthernet 1 is necessary.

I think the dead-lock happens if you select a non Ethernet card (another limitation of libpcap usage). We should then clear the interface.

**Comment by audetto** [comment]
This https://github.com/audetto/AppleWin/commit/275d788d9896e0ebe0a09b9a0baef6d83ca8f2c8 should fix the impossibility to recover from a non-ethernet interface.

**Comment by oliverschmidt** [comment]
I can confirm that that recovery from non-Ethernet interface configuration now works :-)

**Comment by audetto** [comment]
![image](https://user-images.githubusercontent.com/212523/149367028-7fd8bf94-6c6f-4abc-826b-1b897bff1fb8.png)


> Talking about that dialog:
> 
>     * I don't want to activate 'TFE support', I want to activate 'Uthernet support'.

done

>     * I don't want to 'activate network wirth VICE', I want to 'activate network with AppleWin'.

done

>     * The URL given isn't clickable nor selectable.

too hard
 
>     * The URL isn't HTTPS (no good in 2022).
>     * The URL just gives a 404.

done

**Comment by audetto** [comment]
Feature has been merged.
