### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by jvernet** [audetto/AppleWin#6]
Hellon

trying to build under Debian 10, have this issue:
`CMAKE_BUILD_TYPE:                
CMAKE_CXX_FLAGS:                  -Wno-multichar -Werror=return-type
CMAKE_CXX_FLAGS_RELEASE:         -O3 -DNDEBUG
CMAKE_CXX_FLAGS_DEBUG:           -g
CMAKE_CXX_FLAGS_RELWITHDEBINFO:  -O2 -g -DNDEBUG
-- Boost version: 1.67.0
-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   program_options
CMake Error at source/frontends/qapple/CMakeLists.txt:7 (add_subdirectory):
  The source directory

    /home/jvernet/Devel/AppleWin/source/frontends/qapple/QHexView

  does not contain a CMakeLists.txt file.

-- Configuring incomplete, errors occurred!
See also "/home/jvernet/Devel/AppleWin/build/CMakeFiles/CMakeOutput.log".
`

Any help ?

**Comment by jvernet** [comment]
I think I have to import an qhexview projetc, done, ok.
Now another error:

`/home/jvernet/Devel/AppleWin/source/frontends/ncurses/configuration.cpp:6:24: erreur fatale : filesystem : Aucun fichier ou dossier de ce type
 #include <filesystem>
`

**Comment by audetto** [comment]
Yes, for some reason git does not initialise submodules by default.
I've had issues with filesystem with different versions of gcc. Which one do you use?

if this is a problem you can simply skip the ncurses interface by commenting out

https://github.com/audetto/AppleWin/blob/master/CMakeLists.txt#L22

**Comment by jvernet** [comment]
Gcc 8. Will try with 10.

**Comment by audetto** [comment]
According to this
https://gcc.gnu.org/onlinedocs/libstdc++/manual/status.html#status.iso.2017
gcc 8.1 has filesystem but requires a special linker flag, which is what I put in the makefile.
Support for gcc < 8.1 is not something I can / want to add.

**Comment by jvernet** [comment]
I have gcc 8.3.0 under Debian 10. #include <experimental/filesystem> work, but now I have 

/home/jvernet/Devel/AppleWin/source/frontends/ncurses/configuration.cpp: In constructor ‘Configuration::Configuration(const string&)’:
/home/jvernet/Devel/AppleWin/source/frontends/ncurses/configuration.cpp:34:12: error: ‘std::filesystem’ has not been declared
   if (std::filesystem::exists(filename))
            ^~~~~~~~~~
make[2]: *** [source/frontends/ncurses/CMakeFiles/applen.dir/build.make:154: source/frontends/ncurses/CMakeFiles/applen.dir/configuration.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:148: source/frontends/ncurses/CMakeFiles/applen.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by audetto** [comment]
then you need

std::experimental::filesystem

**Comment by audetto** [comment]
I've removed dependency on std::filesystem and fix a compilation error in master.
Soon mockingbird will become the new master but it is not 100% ready yet.

**Comment by audetto** [comment]
filesystem not required any longer
