### ISSUE TITLE
[wish] Synchronizing version with Windows version of AppleWin

### ISSUE THREAD

**Issue by FredBezies** [audetto/AppleWin#60]
Hello.

Could it be possible to synchronize version between your port and the official AppleWin?

Something like 7 years without a new tag, it is kinda long :)

**Comment by audetto** [comment]
I am not sure where you get the 7 years from.

I am 934 commits ahead, and **none** behind.

![image](https://user-images.githubusercontent.com/212523/148698327-ac06de58-7dc0-4b25-a66b-d7ce970662c5.png)

So right now, the code is fully synchronised.

It does not lag more that a few weeks normally.

**Comment by FredBezies** [comment]
I was thinking a sync between the tag used and the about from the emulator.

My package version is: 1.25.0.4.r2185.gd0601d15-1

When I launched Applewin and when I open help/about I got "based on AppleWin 1.30.7.0"

![Capture d’écran de 2022-01-09 21-03-25](https://user-images.githubusercontent.com/8571419/148698767-cafc2735-fb4e-4bf8-ba85-2d8a9b410088.png)

Telling this is also AppleWin for Linux version 1.30.7.0.

I hope I'm more clear now :)

**Comment by audetto** [comment]
> My package version is: 1.25.0.4.r2185.gd0601d15-1

Where is this coming from?

**Comment by audetto** [comment]
I have created one, but I am not going to keep them synchronised. It it going to take me too much time.

**Comment by FredBezies** [comment]
I just wanted to tell: what about a new tag on the code? Not every single release from the official source, but once in a while will be perfect.

**Comment by audetto** [comment]
I read the comments on your AUR page.
Unfortunately without a running arch I cannot create a AUR account to comment.

But `If you want to use uthernet, you must enter in a command line: sudo setcap cap_net_raw=ep ./sa2` is only true if you use `libpcap` which you aren't.

**Comment by audetto** [comment]
I've changed the cmake files to read the version from the resources.

https://github.com/audetto/AppleWin/commit/726b05cdbe8e20d8cc569b6bcdeac950504cb851

you could do the same.
