### ISSUE TITLE
Doesnt compile on latest ubuntu linux

### ISSUE THREAD

**Issue by Ntemis** [audetto/AppleWin#69]
CMake Error at /usr/share/cmake-3.22/Modules/FindPkgConfig.cmake:890 (message):
  None of the required 'minizip' found
Call Stack (most recent call first):
  source/CMakeLists.txt:6 (pkg_search_module)

dpkg -L minizip
/.
/usr
/usr/bin
/usr/bin/miniunzip
/usr/bin/minizip
/usr/share
/usr/share/doc
/usr/share/doc/minizip
/usr/share/doc/minizip/copyright
/usr/share/man
/usr/share/man/man1
/usr/share/man/man1/miniunzip.1.gz
/usr/share/man/man1/minizip.1.gz
/usr/share/doc/minizip/changelog.Debian.gz

**Comment by audetto** [comment]
Which latest exactly?

Have you tried to install all of these?
https://github.com/audetto/AppleWin/blob/master/source/linux/raspbian.list.txt

**Comment by Ntemis** [comment]
libminizip-dev was missing :dancers:
