### ISSUE TITLE
README.md issues

### ISSUE THREAD

**Issue by nerun** [audetto/AppleWin#70]
When I open the Audetto/AppleWin homepage on GitHub i get this one:
![right](https://i.postimg.cc/479JN9Hg/right.png)

But when i click in README.md i get this one (Windows AppleWin README instead of Audetto):
![wrong](https://i.postimg.cc/N28BRvxC/wrong.png)

The same "change" occurs with git clone and by clicking green button > download zip. But everythings works and compiles well.

**Comment by audetto** [comment]
When I click your images, they dont work, and I cannot see what you mean as they are too small.

**Comment by nerun** [comment]
This:
https://github.com/audetto/AppleWin/blob/master/README.md

**Comment by audetto** [comment]
There are 2.
I did not want to delete the one from AW.

https://github.com/audetto/AppleWin/blob/master/.github/README.md
