### ISSUE TITLE
Full Screen with correct aspect ratio?

### ISSUE THREAD

**Issue by skoregon** [audetto/AppleWin#76]
Is there a way to run AppleWin in bullseye/xfce that will run it full screen (not windowed) but maintain the correct aspect ratio (i.e. just put black bars on the unused portion of the screen for a 1366x768 screen rather than stretch the AppleWin image to fill the screen?

**Comment by audetto** [comment]
not at the moment. I need to learn how to do it.

**Comment by skoregon** [comment]
I am not much of a programmer, but perhaps some of these links would be helpful about aspect ratio control?
https://wiki.libsdl.org/SDL2/SDL_RenderSetLogicalSize
https://bumbershootsoft.wordpress.com/2018/10/26/aspect-corrected-image-scaling-with-sdl2/https://benedicthenshaw.com/soft_render_sdl2.html

**Comment by audetto** [comment]
It is available in the command line and in the settings menu.

**Comment by skoregon** [comment]
Thank you so much!  It works perfectly now for aspect-correct display!
