### ISSUE TITLE
Libretto core progress (mockingbird)

### ISSUE THREAD

**Issue by skoregon** [audetto/AppleWin#86]
Are there plans to push ahead with mockingboard support in the libretto core?  I would love to be able to have a front end for AppleWin on linux that lets users easily select games and provides some information about the game (screen shot/etc).  I know about Total Replay but would love to be able to have it be so easy with other games (or at least easier than having to use the finder.)

**Comment by audetto** [comment]
This was already implemented, but not enabled.
There is a new retro options to switch between speaker and mockingboard.

I could enable them both, but I need to merge the 2 audio streams, which I have never done.
