### ISSUE TITLE
"Error creating timer" when resuming in debugger

### ISSUE THREAD

**Issue by sh95014** [audetto/AppleWin#91]
1. System→Debugger
2. Click [Continue]
3. Observe "Error creating timer" message in stderr.

This seems to be due to `winuser.cpp`'s `SetTimer()` function always returning 0, causing `SoundCore_StartTimer()` to complain.

(Observed in macOS, presumed to also occur in Linux from code inspection.)

**Comment by audetto** [comment]
It has always been the case.

I could see it can be turned into a no-op so it does not print anything, but there would be no difference to the emulator.
