### ISSUE TITLE
Audio callback change causes macOS app to hang

### ISSUE THREAD

**Issue by sh95014** [audetto/AppleWin#98]
With the audio callback changes from upstream, the macOS app hangs in the emulator.

At:
```
        myStartCycles += g_nCpuCyclesFeedback;
```
it appears that `myStartCycles` ends up as `18,446,744,073,709,450,416` if `g_nCpuCyclesFeedback` turns out to be negative (-4,600 in my tests), which seems to be a valid scenario given this code in `Speaker.cpp`:
```
	const int nErrorMax = SoundCore_GetErrorMax();				// Cap feedback to +/-nMaxError units
	if(nNumSamplesError < -nErrorMax) nNumSamplesError = -nErrorMax;
	if(nNumSamplesError >  nErrorMax) nNumSamplesError =  nErrorMax;
	g_nCpuCyclesFeedback = (int) ((double)nNumSamplesError * g_fClksPerSpkrSample);
```
(On `sa2` the value of `myStartCycles` is a more modest 7,755,806.)

Anyway, the C "usual arithmetic conversions" would've converted `g_nCpuCyclesFeedback` to unsigned, which is not likely your intention with this code at all, so I'm filing this here even though you're not seeing the bug manifest.

Changing that to:
```
      if (g_nCpuCyclesFeedback > 0) {
        myStartCycles += g_nCpuCyclesFeedback;
      }
```
appears to work around the problem, but I don't understand `g_nCpuCyclesFeedback` enough to say if that's the right fix. Please advise.

**Comment by audetto** [comment]
Rejecting a negative `g_nCpuCyclesFeedback` is not correct, since it would not allow the emulator to slow down if too much audio is generated, with the eventual effect of going past the read pointer.

What is dangerous in the current code is usage of `uint64_t` with in what is effectively signed arithmetic.
Probably better if I replace everything with `int64_t`.

The real issue, though is unclear.
Make sure you never touch `g_nCumulativeCycles` without resetting the Speed too.

I wonder if this *adaptive* speed is really worth it. It still works better, but the FixedSpeed is not far off, and more robust.

**Comment by sh95014** [comment]
On both Mariani (macOS app) and sa2, I see `g_nCpuCyclesFeedback` quickly max out at -4,600:

```
Spkr_SubmitWaveBuffer: g_nCpuCyclesFeedback = 0.000000 * 23.000000
...
Spkr_SubmitWaveBuffer: g_nCpuCyclesFeedback = 0.000000 * 23.000000
Spkr_SubmitWaveBuffer: g_nCpuCyclesFeedback = -20.000000 * 23.000000
Spkr_SubmitWaveBuffer: g_nCpuCyclesFeedback = -40.000000 * 23.000000
Spkr_SubmitWaveBuffer: g_nCpuCyclesFeedback = -60.000000 * 23.000000
Spkr_SubmitWaveBuffer: g_nCpuCyclesFeedback = -80.000000 * 23.000000
Spkr_SubmitWaveBuffer: g_nCpuCyclesFeedback = -100.000000 * 23.000000
```

However, I think sa2 never runs into the signed-unsigned problem because it manages to call `SetFullSpeed()` and reset `g_nCpuCyclesFeedback` to 0 before the bad math in `getCyclesTillNext` destroys `myStartCycles`.

On Mariani, a call to `getCyclesTillNext` seems to be triggered by an excessively long execution frame where I spent about 60 ms setting up the CoreAudio pipeline. Oddly enough, that doesn't seem to cause `ExecuteInRunningMode()` to immediately run practically forever, but it eventually does.

I tried moving the CoreAudio initialization to the constructor and it does sidestep the problem.

But given that `g_nCumulativeCycles` itself is declared `__int64` I think the more thorough fix is going with `int64_t` for the related variables.

**Comment by audetto** [comment]
A negative `g_nCpuCyclesFeedback` means your emulator is going too fast, not slow.

What is strange is that, at the same time `g_nCumulativeCycles` should be a big number, so the maths should still generate a positive number.

You seem to have a small `g_nCumulativeCycles` and a very negative `g_nCpuCyclesFeedback` which I cant explain.

>But given that g_nCumulativeCycles itself is declared __int64 I think the more thorough fix is going with int64_t for the related variables.

It is `unsigned __int64 g_nCumulativeCycles`, but I agree *signed* would make all of this easier to handle.

**Comment by sh95014** [comment]
> You seem to have a small g_nCumulativeCycles and a very negative g_nCpuCyclesFeedback which I cant explain.

My logging indicated that `g_nCpuCyclesFeedback` is negative because `nNumSamplesError` kept growing negative, which from code inspection would be due to the “need less data” case.

I haven’t quite wrapped my head around the logic yet, unfortunately.

> It is unsigned __int64 g_nCumulativeCycles

Ack!  :)

**Comment by audetto** [comment]
Is your audio callback actually consuming audio?

**Comment by sh95014** [comment]
By "consume" you mean call `Read()` on the `IDirectSoundBuffer`? If so, yes.

I added some debug logs, and they're showing that the buffer can get quite big:

```
0x6000003ea598: 33068 - 2048 (2048 + 0) = 31020 bytes in buffer
0x6000003ea598: 31020 - 2048 (2048 + 0) = 28972 bytes in buffer
0x6000003ea598: 29076 - 2048 (2048 + 0) = 27028 bytes in buffer
...a good long time later...
0x6000003ea598: 18208 - 2048 (2048 + 0) = 16160 bytes in buffer
```

(The above shows that CoreAudio is asking for 2KB per frame, but we started out with nearly 33KB in the buffer according to `GetBytesInBuffer()`.)

On a whim I added a "bankruptcy" check to discard the buffer if it's >5x greater than what CoreAudio is asking for on each frame, but it seems to hardly make a dent:

```
0x6000007805b8: 24824 - 2048 (2048 + 0) = 22776 bytes in buffer
0x6000007805b8: bankrupt: 0 bytes in buffer
0x6000007805b8: 24960 - 2048 (2048 + 0) = 22912 bytes in buffer
```

So it looks like I made AppleWin generate a lot more audio than I can digest on the output side. Ideas?

**Comment by audetto** [comment]
So AW wants a buffer about half full. it will start with that amount of silence and use the feedback to keep it so. In sa2 there is a new flag to select the size of the callback buffer. Default to about 30/40 ms, i forgot now. Smaller is better, if your machine is fast enough. If you chose too big of a size (>150) it will underrun a lot.

But the average size read per second needs to be 44100 * 2 in all cases.

**Comment by sh95014** [comment]
I'm getting pretty consistently:
```
DirectSoundRenderProc 0x6000017e3978: 89088 bytes in 1.010s (88199.620 bytes/s)
DirectSoundRenderProc 0x6000017e3978: 89088 bytes in 1.010s (88201.301 bytes/s)
DirectSoundRenderProc 0x6000017e3978: 89088 bytes in 1.010s (88203.514 bytes/s)
```
for the built-in speaker, so that's looking reasonable.

**Comment by audetto** [comment]
Add these lines to Speaker.cpp:765

```
{
using namespace std::chrono;
const auto ms = duration_cast<milliseconds>(system_clock::now().time_since_epoch()).count();
const auto msIn1Minute = 1000 * 60;
std::cout << (ms % msIn1Minute) << "," << nNumSamples << "," << nBytesRemaining << "," << nNumSamplesError << "," << g_nCpuCyclesFeedback << std::endl;
}
```

I get a picture like this.

![image](https://github.com/audetto/AppleWin/assets/212523/c06caf21-68fb-4716-8d73-ec0a6833e0c6)

I think there was an underrun, and you can see the buffer slowly going back to its target.

Given the complexity of this, I will propose to AW a change to generate such a chart (`ifdef`'d out)

**Comment by sh95014** [comment]
Assuming that you're graphing `nBytesRemaining` and `g_nCpuCyclesFeedback`, here's what I'm getting:

<img width="1117" alt="Screenshot 2023-06-16 at 10 14 27 AM" src="https://github.com/audetto/AppleWin/assets/95387068/f1d65c3d-a0e6-4ab4-9b49-f717899bbf5c">

**Comment by audetto** [comment]
The scheduling of the cpu or the audio callback seems odd.

What about this in sdirectsound.cpp:75

```
  void DirectSoundGenerator::audioCallback(uint8_t* stream, int len)
  {
    LPVOID lpvAudioPtr1, lpvAudioPtr2;
    DWORD dwAudioBytes1, dwAudioBytes2;
    const size_t sizeOfBuffer = myBuffer->GetBytesInBuffer();
    const size_t bytesRead = myBuffer->Read(len, &lpvAudioPtr1, &dwAudioBytes1, &lpvAudioPtr2, &dwAudioBytes2);

    {
      using namespace std::chrono;
      const auto ms = duration_cast<milliseconds>(system_clock::now().time_since_epoch()).count();
      const auto msIn10Minute = 1000 * 60 * 10;
      std::cout << (ms % msIn10Minute) << "," << sizeOfBuffer << "," << len << "," << bytesRead << std::endl;
    }

    myMixerBuffer.resize(bytesRead);

```

I get a very regular picture, the audio callback happens in chunks of 4096 bytes for me. What do you have?

![image](https://github.com/audetto/AppleWin/assets/212523/998fedd0-7715-40f6-9c45-12034beaa286)

You can disable the whole feedback with `SoundCore_SetErrorInc(0)`

**Comment by audetto** [comment]
I wonder if there is a potential underrun behaviour problem.
As soon as there is an underrun, the buffer goes from empty to full, which means the feedback will reduce the speed further, probably contributing to the next underrun, but with a circular buffer I don't know what else to do.

And opposite for an overrun, cpu too fast, buffer goes full to empty, feedback makes it faster.

For the whole thing to work, the feedback must keep it away from the boundaries.

This works well for `sa2` unless I move it to the background, but that has always been an issue, I suspect between X11 / Wayland / OpenGL and SDL.

**Comment by sh95014** [comment]
<img width="817" alt="Screenshot 2023-06-17 at 10 03 34 AM" src="https://github.com/audetto/AppleWin/assets/95387068/ee385cc8-12db-4c77-8757-629dbfd7d9d3">

> I get a very regular picture, the audio callback happens in chunks of 4096 bytes for me. What do you have?

I'm seeing consistent calls for 1024 bytes each, ~89,088 bytes/s.

> cpu too fast, buffer goes full to empty, feedback makes it faster.

I don't think that can be a problem... the whole point of the audio callbacks should be to pull only what is needed to play, and a faster CPU shouldn't pull any more audio than a slower one.

Just to be clear though, after the signedness fixes I'm not seeing a serious problem here†, in case you have other things you'd rather be investigating.

† The boot-up beep seems a bit garbled, but audio seems fine afterwards in both latency and quality for basic purposes.

**Comment by audetto** [comment]
Fine, if it works good.
The long flat part seems too good to be true, a perfect synchronisation between cpu and the callback, but hey, not something to complain.

**Comment by sh95014** [comment]
> The long flat part seems too good to be true

The emulator was sitting idle, so that seems plausible.

With enhanced disk speed off, booting to Karateka's crack screen:

<img width="872" alt="Screenshot 2023-06-17 at 11 09 19 AM" src="https://github.com/audetto/AppleWin/assets/95387068/ff8daad0-c136-4a74-b67d-4d21dd128c33">

Between 402078 and 411598, bufferSize has
- average: 8237.5
- min: 8176
- max: 8270
so the steady state is very consistent.

**Comment by audetto** [comment]
I guess this has been solved?

**Comment by shuang886** [comment]
Yeah, not seeing this anymore. Thanks!
